### PR TITLE
Updated zuul GitHub permissions

### PR DESCRIPTION
**Pull request by jfbourque**

### CODE REVIEW

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Review by sduthil — APPROVED** [review]

**Comment by jfbourque** [comment]
failed pr

**Pull request closed without merging**
